name: 'action-ts-eslint-leaderboard'
description: 'Generate a leaderboard based on eslint-disable comments removed'
author: 'john-waitforit'
inputs:
  ignorePattern:
    required: false
    description: 'Path to be ignored when computing score'
    default: ''
outputs:
  pr-comment:
    description: 'The content of the comment that can be put in a pull request comment'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'bar-chart-2'  
  color: 'yellow'
